import type { Metadata } from 'next'
import Link from 'next/link';
import Image from 'next/image';

import './globals.css'
import logoMTS from "../img/logo-eco.svg"


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
            <header>
                <div id="header-wrapper">
                    <Image 
                        alt='Mount'
                        src={logoMTS}
                        // fill
                        // sizes='48px'
                        style={{
                            alignItems: "center",
                            margin: "0px 20px 0px 0px",
                        }}
                    />
                    <nav id="menu-navigation">
                        <Link href="/">
                            <div id="link">Home</div>
                        </Link>
                        <Link href="/lectures">
                            <div id="link">Lectures</div>
                        </Link>
                    </nav>
                    <Link href="/login" className='login'>
                        <div>Войти</div>
                    </Link>
                </div>
            </header>
            <main>
                {children}
            </main>
        </body>
    </html>
  )
}
